### PR TITLE
XCS-185: Inconsistent breadcrumb styling across wikis

### PR DESCRIPTION
**Pull request by KebirYacine**
i have removed the other customizations

### CODE REVIEW

**Comment by evalica** [comment]
This is the right direction. It would be better to remove also the other customizations: for color and bg.

**Comment by evalica** [comment]
The changes are good. 
I've look a bit more at the breadcrumbs customisations and apparently in the "Advanced" sections of the lesscode there are these added rules:

```
// Breadcrumb
ol#hierarchy {
border:@light-border;
}
```

We should remove them

**Comment by KebirYacine** [comment]
Breadcrumb code removed

**Comment by evalica** [comment]
Thank you Yacine!

**Comment by KebirYacine** [comment]
You're welcome

**Pull request merged**
